# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Increment the build number and save it back to the Xcode project
    increment_build_number(
      xcodeproj: "I am Groot.xcodeproj",
    )

    # Build the app with the updated build number
    build_app(
      scheme: "I am Groot",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "io.appnap.iamgroot" => "Sarwar Apple Distribution - I am Groot"
        }
      }
    )

    # Upload to TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: false,
      api_key: {
        key_id: "5J2W9834L7",
        issuer_id: "0b5682ab-82e4-4112-9212-1175b2c5ab55",
        key: "-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKQMTp3SQDxkXVKSi\nYU/JDvRFxflKZTwe++RdOnAh3lagCgYIKoZIzj0DAQehRANCAATc7z8e5h1N0Bwl\no7jThziy/hgprsL7rWoMymgew0brCNolhDuUUqStCaGL6re8jaWm2nUFmrx9eJGV
6L4YbI3l\n-----END PRIVATE KEY-----"
      }
    )

    # Set app encryption declaration
    set_app_encryption_declaration(
      app_identifier: "io.appnap.iamgroot",
      username: ENV["APPLE_ID"],
      team_id: "L3D3A22YK5",
      uses_encryption: false,
      export_compliance_uses_encryption: false,
      encryption_updated: false,
      is_exempt: false,
      contains_third_party_cryptography: false,
      available_on_french_store: true
    )
  end
end



