default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Increment the build number and save it back to the Xcode project
    increment_build_number(
      xcodeproj: "I am Groot.xcodeproj",
    )

    # Build the app with the updated build number
    build_app(
      scheme: "I am Groot",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "io.appnap.iamgroot" => "Sarwar Apple Distribution - I am Groot"
        }
      }
    )

    # Upload to TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: false,
      api_key: {
        key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
        issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
        key_filepath: './AuthKey.p8'
      }
    )
  end
end
