name: 'Build and Deploy iOS app'

on:
    push:
        branches:
            - main

jobs:
    build_and_deploy:
        runs-on: macos-latest

        steps:
            - name: checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  brew install ruby
                  sudo gem install fastlane -NV
                  bundle install

            - name: Install the Apple certificate and provisioning profile
              env:
                  BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_DISTRIBUTION_CERTIFICATE_BASE64 }}
                  P12_PASSWORD: ${{ secrets.P12_DISTRIBUTION_PASSWORD }}
                  APP_STORE_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_DISTRIBUTION_PROVISION_PROFILE_BASE64 }}
                  KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
              run: |
                  CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
                  PP_PATH=$RUNNER_TEMP/app_store_pp.mobileprovision
                  KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
                  echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
                  echo -n "$APP_STORE_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
                  security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
                  security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
                  security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
                  security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
                  security list-keychain -d user -s $KEYCHAIN_PATH
                  mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
                  cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

            - name: Run Fastlane
              env:
                  APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
                  APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
                  APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }}
              run: |
                  fastlane beta
